/*

Copyright 2009 Marc Suñe Clos, Isaac Gelado

This file is part of the NetGPU framework.

The NetGPU framework is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

The NetGPU framework is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

*/

/*Do not edit this file if you don't know what you are doing */

/*** Undefs previous MACROS ***/

/* General MACROS */
#undef ANALYSIS_NAME 
#undef ANALYSIS_INPUT_TYPE
#undef ANALYSIS_OUTPUT_TYPE
#undef ANALYSIS_TPB
#undef ADVANCED_MODE


#undef DATA_ELEMENT
#undef RESULT_ELEMENT


#undef NUM_OF_USER_SYNCBLOCKS 
#undef _PRECODED_COUNTER 
#undef ITERATOR__
#undef SYNCBLOCKS 
#undef SYNCBLOCKS_PRECODED

#undef MULTIKERNEL_OPERATION_PERFORMED 

/* WINDOWS */
#undef HAS_WINDOW 
#undef WINDOW_TYPE 
#undef WINDOW_LIMIT 

/* Undefs modules and submodules */
#undef LOAD_RATE_THRESHOLDS_ANALYSIS_MODULE
#undef LOAD_DETECTOR_THRESHOLDS_ANALYSIS_MODULE
#undef LOAD_FLOW_THRESHOLDS_ANALYSIS_MODULE

/* Undefs SIZE MACROS (Threshold module)*/
#undef KB
#undef MB
#undef GB

/* Others */	
#undef SHARED_BUFFER_SIZE

/*** Loads basic types ***/
#include <inttypes.h>
#include "Windows.h"
#include "InitCounter.def"
