/* 
	MODULE:Throughputs DB dumper 
	TYPE: Hook

	PrePreprocessor orders (ppp.sh):

	###PATTERNS $THROUGHPUTS$DB_DUMPER$DUMP_ALARMS(

*/

//#warning  Throughputs Database Dumper Hook loaded

#include <iostream>
#include <sstream>
#include "../hostTimeUtils.h"

using namespace std;

#define $THROUGHPUTS$DB_DUMPER$PREPARE_TO_DUMP_ALARMS()\
	$THROUGHPUTS$DB_DUMPER$PREPARE_TO_DUMP_ALARMS_TO_DBTABLE(STR(ANALYSIS_NAME))
	
//	COMPOUND_NAME(ANALYSIS_NAME,dump_ipscan_alarms_to_db_table)(packetBuffer,results,state,auxBlocks,STR(ANALYSIS_NAME),(float)severe,(float)critical)
/*
template<typename R>
void inline COMPOUND_NAME(ANALYSIS_NAME,dump_ipscan_alarms_to_db_table)(PacketBuffer* packetBuffer,R* results, analysisState_t  state, int64_t* auxBlocks,char* tableName,float severe,float critical){
*/

#define $THROUGHPUTS$DB_DUMPER$PREPARE_TO_DUMP_ALARMS_TO_DBTABLE(tableName)\
	do{\
		int i,j;\
		bool hasResults;\
		stringstream total;\
		stringstream fixed;\
		static string to_db;\
		fixed <<"INSERT INTO "<<tableName<<" ";\
		stringstream tmp_ids;\
		stringstream tmp_values;\
\
		for(i = 0,hasResults = false;i<state.windowState.totalNumberOfBlocks;i++){\
			for(j = 0;j<auxBlocks[i];j++,total.str(""),tmp_values.str(""),tmp_ids.str("")){\
			if(results[i].rate > 0){\
				hasResults = true;\
				tmp_ids<<"counter,rate,flow,starttime,endtime,dumped";\
				tmp_values<<results[i*ANALYSIS_TPB+j].counter<<","<<results[i*ANALYSIS_TPB+j].rate<<","<<results[i*ANALYSIS_TPB+j].flow<<","<<state.windowState.windowStartTime.tv_sec<<","<<state.windowState.windowEndTime.tv_sec<<",NOW()"






#define $THROUGHPUTS$DB_DUMPER$DUMP_ALARMS()\
				total<<fixed.str()<<" ("<<tmp_ids.str()<<") values ("<<tmp_values.str()<<");";\
				to_db =  (total.str());\
				ANALYSIS_NAME::queryManager.scheduleQuery(to_db.c_str());\
				}\
			}\
		}\
		if(hasResults){\
			ANALYSIS_NAME::queryManager.executePackedQuerys();\
		}\
	}while(0)


//Simple types
#define $THROUGHPUTS$DB_DUMPER$ADD_FIELD(mappingToDB)\
	tmp_ids<<","<<STR(mappingToDB);\
	tmp_values<<","<<results[i*ANALYSIS_TPB+j].user

#define $THROUGHPUTS$DB_DUMPER$ADD_FIELD_AS_IP(mappingToDB)\
	tmp_ids<<","<<STR(mappingToDB);\
	tmp_values<<",CAST("<<results[i*ANALYSIS_TPB+j].user<<" as bit(32))"


//Structure types

#define $THROUGHPUTS$DB_DUMPER$ADD_FIELD_COMPLEX(field,mappingToDB)\
	tmp_ids<<","<<STR(mappingToDB);\
	tmp_values<<","<<results[i*ANALYSIS_TPB+j].user.field

#define $THROUGHPUTS$DB_DUMPER$ADD_FIELD_AS_IP_COMPLEX(field,mappingToDB)\
	tmp_ids<<","<<STR(mappingToDB);\
	tmp_values<<",CAST("<<results[i*ANALYSIS_TPB+j].user.field<<" as bit(32))"



