/* 
	MODULE:Detector
	TYPE: Analysis

	PrePreprocessor orders (ppp.sh): 

	###PATTERNS $DETECTORS$ANALYSIS();

*/


#include "Thresholds.h"
//#warning "Detector analysis module Loaded"
#include "Rates.module"

/*CHECK OF DATA_ELEMENT REDEFINITION AT THE END OF THE FILE */

/***** DETECTOR ANALYSIS *****/

#define $DETECTORS$ANALYSIS() \
	COMPOUND_NAME(ANALYSIS_NAME,preDefinedAnalysisCodeRateThreshold)(GPU_buffer,GPU_data,GPU_results,state,0);\
	__syncthreads()
/***** END OF DETECTOR ANALYSIS *****/





